name: Release
on:
    push:
        branches:
            - master
jobs:
    release:
        if: contains(github.event.commits[0].message, '[skip ci]') == false
        runs-on: ubuntu-18.04
        steps:
            - uses: actions/checkout@v1
            - name: Use Node.js 12.x
              uses: actions/setup-node@v1
              with:
                  node-version: '12.x'
            - name: Install dependencies
              run: npm ci
            - name: Build sources
              run: npm run build
            - name: Lint sources
              run: npm run lint
            - name: Run tests
              run: npm test
              env:
                  CI: true
            - name: Release
              env:
                  GH_TOKEN: ${{ secrets.GH_TOKEN }}
              run: npx semantic-release
